<?php

namespace Database\Seeders;

use App\Models\Language;
use App\Models\LanguageDetail;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LanguageKeywordsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $languages = Language::select(['_id', 'code'])->get();

        $homekeywords = [
            ['keyword' => 'languages', 'translated' => 'Languages'],
            ['keyword' => 'privacyAndTerms', 'translated' => 'Privacy & Terms'],
            ['keyword' => 'signIn', 'translated' => 'Sign In'],
            ['keyword' => 'typeYourEmail', 'translated' => 'Type your E-Mail'],
            ['keyword' => 'typeYourPasswordHere', 'translated' => 'Type Your password Here'],
            ['keyword' => 'rememberMe', 'translated' => 'Remember Me'],
            ['keyword' => 'lostDevice', 'translated' => 'Lost Device'],
            ['keyword' => 'addNewDevice', 'translated' => 'Add New Device'],
            ['keyword' => 'password', 'translated' => 'Password'],
            ['keyword' => 'forgotPassword', 'translated' => 'Forgot Password'],
            ['keyword' => 'loginError', 'translated' => 'Login Error'],
            ['keyword' => 'theEmailAddressYouProvidedDoesNotCorrespondWithTheDeviceIdAssociatedWithTheAccount', 'translated' => 'The email address you provided does not correspond with the device ID associated with the account'],
            ['keyword' => 'newDevice', 'translated' => 'New Device'],
            ['keyword' => 'setupANewDevice', 'translated' => 'Setup a new device'],
            ['keyword' => 'emailVerification', 'translated' => 'Email Verification'],
            ['keyword' => 'send', 'translated' => 'Send'],
            ['keyword' => 'weWillSendAMailToTheEmailAddressWithACodeCheckSpamFolder', 'translated' => 'We will send a mail to the email address with a Code “Check Spam Folder”'],
            ['keyword' => 'emailSentTo', 'translated' => 'E-Mail sent to'],
            ['keyword' => 'codeVerification', 'translated' => 'Code Verification'],
            ['keyword' => 'anAuthenticationCodeHasBeenSentTo', 'translated' => 'An authentication code has been sent to'],
            ['keyword' => 'iDidntReceiveCode', 'translated' => "I didn't receive code?"],
            ['keyword' => 'resendCode', 'translated' => 'Resend Code'],
            ['keyword' => 'secLeft', 'translated' => 'Sec left'],
            ['keyword' => 'verifyNow', 'translated' => 'Verify Now'],
            ['keyword' => 'changeDevice', 'translated' => 'Change Device'],
            ['keyword' => 'start', 'translated' => 'Start'],
            ['keyword' => 'connecting', 'translated' => 'Connecting'],
            ['keyword' => 'summary', 'translated' => 'Summary'],
            ['keyword' => 'status', 'translated' => 'Status'],
            ['keyword' => 'startNow', 'translated' => 'Start Now'],
            ['keyword' => 'yourNewDevice', 'translated' => 'Your new Device'],
            ['keyword' => 'yourOldDevice', 'translated' => 'Your Old Device'],
            ['keyword' => 'deviceId', 'translated' => 'Device ID'],
            ['keyword' => 'deviceRegistration', 'translated' => 'Device Registration'],
            ['keyword' => 'disconnectOldDevice', 'translated' => 'Disconnect old Device'],
            ['keyword' => 'takeMeToSignIn', 'translated' => 'Take me to Sign in'],
            ['keyword' => 'close', 'translated' => 'Close'],
            ['keyword' => 'selectGender', 'translated' => 'Select Gender'],
            ['keyword' => 'imFemale', 'translated' => "I'm Female"],
            ['keyword' => 'imMale', 'translated' => "I'm Male"],
            ['keyword' => 'back', 'translated' => 'Back'],
            ['keyword' => 'next', 'translated' => 'Next'],
            ['keyword' => 'error', 'translated' => 'Error'],
            ['keyword' => 'failedToGetCurrentLocationPleaseMakeSureLocationServicesAreEnabled', 'translated' => 'Failed to get current location. Please make sure location services are enabled.'],
            ['keyword' => 'pleaseEnterAnAddressBeforeProceeding', 'translated' => 'Please enter an address before proceeding.'],
            ['keyword' => 'selectCountry', 'translated' => 'Select Country'],
            ['keyword' => 'currentLocation', 'translated' => 'Current location'],
            ['keyword' => 'yourLocation', 'translated' => 'Your Location'],
            ['keyword' => 'yourCurrentLocation', 'translated' => 'Your current location'],
            ['keyword' => 'cameraNotAvailable', 'translated' => 'Camera not available'],
            ['keyword' => 'aboutYou', 'translated' => 'About You'],
            ['keyword' => 'yourFirstname', 'translated' => 'Your Firstname'],
            ['keyword' => 'yourLastname', 'translated' => 'Your Lastname'],
            ['keyword' => 'yourUsername', 'translated' => 'Your Username'],
            ['keyword' => 'anErrorOccurredWhileSubmittingTheFormPleaseTryAgainLater', 'translated' => 'An error occurred while submitting the form. Please try again later.'],
            ['keyword' => 'anUnknownErrorOccurred', 'translated' => 'An unknown error occurred'],
            ['keyword' => 'step', 'translated' => 'Step'],
            ['keyword' => 'yourStatus', 'translated' => 'Your Status'],
            ['keyword' => 'single', 'translated' => 'Single'],
            ['keyword' => 'engaged', 'translated' => 'Engaged'],
            ['keyword' => 'married', 'translated' => 'Married'],
            ['keyword' => 'yourBirthday', 'translated' => 'Your Birthday'],
            ['keyword' => 'information', 'translated' => 'Information'],
            ['keyword' => 'uMustBeAtLeast16YearOld', 'translated' => 'You must be at least 16 years old'],
            ['keyword' => 'confirm', 'translated' => 'Confirm'],
            ['keyword' => 'yourOrigin', 'translated' => 'Your Origin'],
            ['keyword' => 'pleaseSelect', 'translated' => 'Please Select'],
            ['keyword' => 'imKurdish', 'translated' => "I'm Kurdish"],
            ['keyword' => 'imNotKurdish', 'translated' => "I'm not Kurdish"],
            ['keyword' => 'selectYourProvince', 'translated' => 'Select your Province'],
            ['keyword' => 'selectYourCity', 'translated' => 'Select your City'],
            ['keyword' => 'kurdistan', 'translated' => 'Kurdistan'],
            ['keyword' => 'yourEmailAddress', 'translated' => 'Your E-Mail Address'],
            ['keyword' => 'emailAddress', 'translated' => 'E-Mail Address'],
            ['keyword' => 'enterYourEmail', 'translated' => 'Enter Your E-Mail'],
            ['keyword' => 'repeatYourEmail', 'translated' => 'Repeat your E-Mail'],
            ['keyword' => 'confirmYourEmail', 'translated' => 'Confirm Your E-Mail'],
            ['keyword' => 'thisEmailAlreadyExists', 'translated' => 'This E-Mail already exists'],
            ['keyword' => 'loginNow', 'translated' => 'Login now'],
            ['keyword' => 'emailDoesntMatch', 'translated' => "E-Mail doesn't match"],
            ['keyword' => 'yourPhoneNumber', 'translated' => 'Your Phone Number'],
            ['keyword' => 'typeYourNumber', 'translated' => 'Type your number'],
            ['keyword' => 'createAPassword', 'translated' => 'Create a Password'],
            ['keyword' => 'enterAPassword', 'translated' => 'Enter a Password'],
            ['keyword' => 'repeatAPassword', 'translated' => 'Repeat a Password'],
            ['keyword' => 'rewriteYourPassword', 'translated' => 'Rewrite your password'],
            ['keyword' => 'hasAtLeast810Characters', 'translated' => 'Has at least 8-10 Characters'],
            ['keyword' => 'hasAnUppercaseLetterOrSymbol', 'translated' => 'Has an uppercase letter or symbol'],
            ['keyword' => 'hasANumbers', 'translated' => 'Has a number'],
            ['keyword' => 'hasPasswordMatched', 'translated' => 'Has password matched'],
            ['keyword' => 'acceptPolicyAndTerms', 'translated' => 'Accept policy and terms'],
            ['keyword' => 'tüBexirHatiUserName', 'translated' => 'Tü Bexir Hati User Name'],
            ['keyword' => 'fromLocation', 'translated' => 'From location'],
            ['keyword' => 'kurdistanRojava10111Qamishlo', 'translated' => 'Kurdistan - Rojava - 10111 Qamishlo'],
            ['keyword' => 'completeYourAccount', 'translated' => 'Complete your Account'],
            ['keyword' => 'accountConfirmation', 'translated' => 'Account Confirmation'],
            ['keyword' => 'anEmailHasBeenSentToYouFollowDirectionInTheEmailToConfirmYourAccount', 'translated' => 'An e-mail has been sent to you. Follow the directions in the e-mail to confirm your Account'],
            ['keyword' => 'pleaseEnterTheOtpCodeYouReceivedThroughEmail', 'translated' => 'Please enter the OTP code you received through email.'],
            ['keyword' => 'accountConfirmedSuccessfully', 'translated' => 'Account confirmed successfully!'],
            ['keyword' => 'unexpectedResponseFromTheServerPleaseTryAgainLater', 'translated' => 'Unexpected response from the server. Please try again later.'],
            ['keyword' => 'anErrorOccurredWhileProcessingYourRequest', 'translated' => 'An error occurred while processing your request.'],
            ['keyword' => 'noResponseFromServerPleaseCheckYourInternetConnection', 'translated' => 'No response from the server. Please check your internet connection.'],
            ['keyword' => 'anUnexpectedErrorOccurredPleaseTryAgainLater', 'translated' => 'An unexpected error occurred. Please try again later.'],
            ['keyword' => 'confirmYourAccount', 'translated' => 'Confirm your Account'],
            ['keyword' => 'weWillSendAMailToTheEmailAddressYouRegisteredToActivateYourAccount', 'translated' => 'We will send a mail to the e-mail address you registered to activate your Account'],
            ['keyword' => 'didntReceiveCode', 'translated' => "Didn't receive code?"],
            ['keyword' => 'resentNow', 'translated' => 'Resent Now'],
            ['keyword' => 'accountCreated', 'translated' => 'Account Created!'],
            ['keyword' => 'yourAccountHadBeedCreatedSuccessfully', 'translated' => 'Your account had been created successfully.'],
            ['keyword' => 'pleaseSignInToUseYourAccountAndEnjoy', 'translated' => 'Please sign in to use your account and enjoy'],
            ['keyword' => 'search', 'translated' => 'Search'],
            ['keyword' => 'enterYourFirstname', 'translated' => 'Enter Your Firstname'],
            ['keyword' => 'enterYourLastname', 'translated' => 'Enter Your Lastname'],
            ['keyword' => 'enterYourUsername', 'translated' => 'Enter Your Username'],
            ['keyword' => 'acceptPolicyAnd', 'translated' => 'Accept policy and'],
            ['keyword' => 'terms', 'translated' => 'terms'],
            ['keyword' => 'pleaseEnterAValidEmail', 'translated' => 'Please enter a valid email.'],
            ['keyword' => 'failedToResetDevicePleaseTryAgain', 'translated' => 'Failed to reset device. Please try again.'],
            ['keyword' => 'weWillSendAMailToTheEmailAddressYouRegisteredToRegainYourPassword', 'translated' => 'We will send a mail to the email address you registered to regain your password.'],
            ['keyword' => 'passwordResetEmailSent', 'translated' => 'Password Reset Email Sent'],
            ['keyword' => 'anEmailHasBeenSentToYouFollowDirectionsInTheEmailToResetYourPassword', 'translated' => 'An email has been sent to you. Follow directions in the email to reset your password.'],
            ['keyword' => 'invalidCode', 'translated' => 'Invalid Code'],
            ['keyword' => 'pleaseEnterThe4DigitOtpCode', 'translated' => 'Please enter the 4-digit OTP code'],
            ['keyword' => 'success', 'translated' => 'Success'],
            ['keyword' => 'otpVerifiedSuccessfully', 'translated' => 'OTP verified successfully!'],
            ['keyword' => 'otpVerificationFailed', 'translated' => 'OTP verification failed'],
            ['keyword' => 'failedToVerifyOtpPleaseTryAgain', 'translated' => 'Failed to verify OTP. Please try again.'],
            ['keyword' => 'resendDisabled', 'translated' => 'Resend Disabled'],
            ['keyword' => 'pleaseWaitUntilTheTimerEndsToResendTheCode', 'translated' => 'Please wait until the timer ends to resend the code.'],
            ['keyword' => 'verification', 'translated' => 'Verification'],
            ['keyword' => 'passwordHasBeenSuccessfullyReset', 'translated' => 'Password has been successfully reset.'],
            ['keyword' => 'passwordResetFailed', 'translated' => 'Password reset failed'],
            ['keyword' => 'noResponseFromTheServerPleaseTryAgain', 'translated' => 'No response from the server. Please try again.'],
            ['keyword' => 'somethingWentWrongPleaseTryAgainLater', 'translated' => 'Something went wrong. Please try again later.'],
            ['keyword' => 'createPassword', 'translated' => 'Create Password'],
            ['keyword' => 'chooseASecurePasswordThatWillBeEasyForYouToRemember', 'translated' => 'Choose a secure password that will be easy for you to remember.'],
            ['keyword' => 'confirmYourPasswordHere', 'translated' => 'Confirm your password here'],
        ];

        $kurdishkeywords = [
            ['keyword' => 'languages', 'translated' => 'Ziman'],
            ['keyword' => 'privacyAndTerms', 'translated' => 'Nepênî û Merc'],
            ['keyword' => 'signIn', 'translated' => 'Têkevin'],
            ['keyword' => 'typeYourEmail', 'translated' => 'E-nameya xwe binivîse'],
            ['keyword' => 'typeYourPasswordHere', 'translated' => 'Şîfreya xwe li vir binivîse'],
            ['keyword' => 'rememberMe', 'translated' => 'Min Bîne Bîra Xwe'],
            ['keyword' => 'lostDevice', 'translated' => 'Amûra Wenda'],
            ['keyword' => 'addNewDevice', 'translated' => 'Amûrek Nû Zêde Bike'],
            ['keyword' => 'password', 'translated' => 'Şîfre'],
            ['keyword' => 'forgotPassword', 'translated' => 'Şîfre Ji Bîr Kir'],
            ['keyword' => 'loginError', 'translated' => 'Çewtiya Têketinê'],
            ['keyword' => 'theEmailAddressYouProvidedDoesNotCorrespondWithTheDeviceIdAssociatedWithTheAccount', 'translated' => 'Navnîşana e-nameya ku we peyda kiriye bi nasnameya cîhaza ku bi hesabê ve girêdayî ye re têkildar nabe'],
            ['keyword' => 'newDevice', 'translated' => 'Amûra Nû'],
            ['keyword' => 'setupANewDevice', 'translated' => 'Amûrek nû saz bike'],
            ['keyword' => 'emailVerification', 'translated' => 'Verastkirina E-nameyê'],
            ['keyword' => 'send', 'translated' => 'Bişîne'],
            ['keyword' => 'weWillSendAMailToTheEmailAddressWithACodeCheckSpamFolder', 'translated' => 'Em ê e-nameyek bi kodek ji navnîşana e-nameyê re bişînin "Pelê Spam Kontrol Bikin"'],
            ['keyword' => 'emailSentTo', 'translated' => 'E-name ji bo şandin'],
            ['keyword' => 'codeVerification', 'translated' => 'Verastkirina Kodê'],
            ['keyword' => 'anAuthenticationCodeHasBeenSentTo', 'translated' => 'Kodek rastnivîsandinê ji bo hate şandin'],
            ['keyword' => 'iDidntReceiveCode', 'translated' => 'Min kod nestand?'],
            ['keyword' => 'resendCode', 'translated' => 'Kodê Ji Nû Ve Bişîne'],
            ['keyword' => 'secLeft', 'translated' => 'Çirk çûn'],
            ['keyword' => 'verifyNow', 'translated' => 'Niha Verast Bike'],
            ['keyword' => 'changeDevice', 'translated' => 'Amûrê Biguherîne'],
            ['keyword' => 'start', 'translated' => 'Destpêk'],
            ['keyword' => 'connecting', 'translated' => 'Girêdan'],
            ['keyword' => 'summary', 'translated' => 'Kurte'],
            ['keyword' => 'status', 'translated' => 'Rewş'],
            ['keyword' => 'startNow', 'translated' => 'Niha Dest Pê Bike'],
            ['keyword' => 'yourNewDevice', 'translated' => 'Amûra weya nû'],
            ['keyword' => 'yourOldDevice', 'translated' => 'Amûra weya kevn'],
            ['keyword' => 'deviceId', 'translated' => 'Nasnameya Amûrê'],
            ['keyword' => 'deviceRegistration', 'translated' => 'Qeydkirina Amûrê'],
            ['keyword' => 'disconnectOldDevice', 'translated' => 'Amûra kevn qut bike'],
            ['keyword' => 'takeMeToSignIn', 'translated' => 'Min Bibe Têketinê'],
            ['keyword' => 'close', 'translated' => 'Bigire'],
            ['keyword' => 'selectGender', 'translated' => 'Zayend Hilbijêre'],
            ['keyword' => 'imFemale', 'translated' => 'Ez Jinim'],
            ['keyword' => 'imMale', 'translated' => 'Ez Nêrim'],
            ['keyword' => 'back', 'translated' => 'Paş'],
            ['keyword' => 'next', 'translated' => 'Piştî'],
            ['keyword' => 'error', 'translated' => 'Çewtî'],
            ['keyword' => 'failedToGetCurrentLocationPleaseMakeSureLocationServicesAreEnabled', 'translated' => 'Bi destxistina cîhê heyî biser neket. Ji kerema xwe pê ewle bine ku karûbarên cîhê çalak in.'],
            ['keyword' => 'pleaseEnterAnAddressBeforeProceeding', 'translated' => 'Ji kerema xwe berî ku hûn bidomînin navnîşek binivîsin.'],
            ['keyword' => 'selectCountry', 'translated' => 'Welat Hilbijêre'],
            ['keyword' => 'currentLocation', 'translated' => 'Cihê niha'],
            ['keyword' => 'yourLocation', 'translated' => 'Cihê we'],
            ['keyword' => 'yourCurrentLocation', 'translated' => 'Cihê weya niha'],
            ['keyword' => 'cameraNotAvailable', 'translated' => 'Kamera ne berdest e'],
            ['keyword' => 'aboutYou', 'translated' => 'Derbarê We'],
            ['keyword' => 'yourFirstname', 'translated' => 'Navê We'],
            ['keyword' => 'yourLastname', 'translated' => 'Paşnavê We'],
            ['keyword' => 'yourUsername', 'translated' => 'Navê Bikarhênerê We'],
            ['keyword' => 'anErrorOccurredWhileSubmittingTheFormPleaseTryAgainLater', 'translated' => 'Di dema şandina formê de çewtiyek çêbû. Ji kerema xwe paşê dîsa biceribînin.'],
            ['keyword' => 'anUnknownErrorOccurred', 'translated' => 'Çewtiyek nenas çêbû'],
            ['keyword' => 'step', 'translated' => 'Gav'],
            ['keyword' => 'yourStatus', 'translated' => 'Rewşa We'],
            ['keyword' => 'single', 'translated' => 'Yekane'],
            ['keyword' => 'engaged', 'translated' => 'Nişanî'],
            ['keyword' => 'married', 'translated' => 'Zewicî'],
            ['keyword' => 'yourBirthday', 'translated' => 'Rojbûna We'],
            ['keyword' => 'information', 'translated' => 'Agahî'],
            ['keyword' => 'uMustBeAtLeast16YearOld', 'translated' => 'Divê hûn herî kêm 16 salî bin'],
            ['keyword' => 'confirm', 'translated' => 'Erêkirin'],
            ['keyword' => 'yourOrigin', 'translated' => 'Esilê We'],
            ['keyword' => 'pleaseSelect', 'translated' => 'Ji Kerema Xwe Hilbijêrin'],
            ['keyword' => 'imKurdish', 'translated' => 'Ez Kurdim'],
            ['keyword' => 'imNotKurdish', 'translated' => 'Ez Ne Kurdim'],
            ['keyword' => 'selectYourProvince', 'translated' => 'Parêzgeha Xwe Hilbijêrin'],
            ['keyword' => 'selectYourCity', 'translated' => 'Bajarê Xwe Hilbijêrin'],
            ['keyword' => 'kurdistan', 'translated' => 'Kurdistan'],
            ['keyword' => 'yourEmailAddress', 'translated' => 'Navnîşana E-nameya We'],
            ['keyword' => 'emailAddress', 'translated' => 'Navnîşana E-nameyê'],
            ['keyword' => 'enterYourEmail', 'translated' => 'E-nameya Xwe Binivîse'],
            ['keyword' => 'repeatYourEmail', 'translated' => 'E-nameya Xwe Dubare Bike'],
            ['keyword' => 'confirmYourEmail', 'translated' => 'E-nameya Xwe Erê Bike'],
            ['keyword' => 'thisEmailAlreadyExists', 'translated' => 'Ev E-name jixwe heye'],
            ['keyword' => 'loginNow', 'translated' => 'Niha Têkeve'],
            ['keyword' => 'emailDoesntMatch', 'translated' => 'E-name li hev nake'],
            ['keyword' => 'yourPhoneNumber', 'translated' => 'Hejmara Telefona We'],
            ['keyword' => 'typeYourNumber', 'translated' => 'Hejmara xwe binivîse'],
            ['keyword' => 'createAPassword', 'translated' => 'Şîfreyek Biafirîne'],
            ['keyword' => 'enterAPassword', 'translated' => 'Şîfreyek binivîse'],
            ['keyword' => 'repeatAPassword', 'translated' => 'Şîfreyek dubare bike'],
            ['keyword' => 'rewriteYourPassword', 'translated' => 'Şîfreya xwe ji nû ve binivîse'],
            ['keyword' => 'hasAtLeast810Characters', 'translated' => 'Bi kêmanî 8-10 tîpan heye'],
            ['keyword' => 'hasAnUppercaseLetterOrSymbol', 'translated' => 'Tîpek mezin an sembolek heye'],
            ['keyword' => 'hasANumbers', 'translated' => 'Hejmarek heye'],
            ['keyword' => 'hasPasswordMatched', 'translated' => 'Şîfre li hev kir'],
            ['keyword' => 'acceptPolicyAndTerms', 'translated' => 'Siyaseta û mercan qebûl bike'],
            ['keyword' => 'tüBexirHatiUserName', 'translated' => 'Navê Bikarhêner Tü Bexir Hati'],
            ['keyword' => 'fromLocation', 'translated' => 'Ji cîh'],
            ['keyword' => 'kurdistanRojava10111Qamishlo', 'translated' => 'Kurdistan - Rojava - 10111 Qamişlo'],
            ['keyword' => 'completeYourAccount', 'translated' => 'Hesaba xwe temam bike'],
            ['keyword' => 'accountConfirmation', 'translated' => 'Tesdîqkirina Hesabê'],
            ['keyword' => 'anEmailHasBeenSentToYouFollowDirectionInTheEmailToConfirmYourAccount', 'translated' => 'E-nameyek ji we re hatiye şandin. Ji bo tesdîqkirina Hesabê xwe rêwerzên di e-nameyê de bişopînin'],
            ['keyword' => 'pleaseEnterTheOtpCodeYouReceivedThroughEmail', 'translated' => 'Ji kerema xwe koda OTP-ê ya ku we bi e-nameyê wergirtiye binivîsin.'],
            ['keyword' => 'accountConfirmedSuccessfully', 'translated' => 'Hesab bi serkeftî hate tesdîqkirin!'],
            ['keyword' => 'unexpectedResponseFromTheServerPleaseTryAgainLater', 'translated' => 'Ji serverê bersivek nediyar hat. Ji kerema xwe paşê dîsa biceribînin.'],
            ['keyword' => 'anErrorOccurredWhileProcessingYourRequest', 'translated' => 'Di dema pêvajoykirina daxwaza we de çewtiyek çêbû.'],
            ['keyword' => 'noResponseFromServerPleaseCheckYourInternetConnection', 'translated' => 'Ji serverê tu bersiv tune. Ji kerema xwe pêwendiya xweya înternetê kontrol bikin.'],
            ['keyword' => 'anUnexpectedErrorOccurredPleaseTryAgainLater', 'translated' => 'Çewtiyek nediyar çêbû. Ji kerema xwe paşê dîsa biceribînin.'],
            ['keyword' => 'confirmYourAccount', 'translated' => 'Hesaba xwe tesdîq bike'],
            ['keyword' => 'weWillSendAMailToTheEmailAddressYouRegisteredToActivateYourAccount', 'translated' => 'Em ê e-nameyek ji navnîşana e-nameya ku we qeyd kiriye bişînin da ku Hesaba we çalak bikin'],
            ['keyword' => 'didntReceiveCode', 'translated' => 'Kod negihaşt?'],
            ['keyword' => 'resentNow', 'translated' => 'Niha Ji Nû Ve Hate Şandin'],
            ['keyword' => 'accountCreated', 'translated' => 'Hesab Hate Afirandin!'],
            ['keyword' => 'yourAccountHadBeedCreatedSuccessfully', 'translated' => 'Hesaba we bi serkeftî hate afirandin.'],
            ['keyword' => 'pleaseSignInToUseYourAccountAndEnjoy', 'translated' => 'Ji kerema xwe têkevin da ku hûn hesaba xwe bikar bînin û kêfê bikin'],
            ['keyword' => 'search', 'translated' => 'Lêgerîn'],
            ['keyword' => 'enterYourFirstname', 'translated' => 'Navê xwe binivîse'],
            ['keyword' => 'enterYourLastname', 'translated' => 'Paşnavê xwe binivîse'],
            ['keyword' => 'enterYourUsername', 'translated' => 'Navê bikarhênerê xwe binivîse'],
            ['keyword' => 'acceptPolicyAnd', 'translated' => 'Rêzokê qebûl bike û'],
            ['keyword' => 'terms', 'translated' => 'Merc'],
            ['keyword' => 'pleaseEnterAValidEmail', 'translated' => 'Ji kerema xwe e-nameya rast binivîse.'],
            ['keyword' => 'failedToResetDevicePleaseTryAgain', 'translated' => 'Ji nû ve saz kirina amûrê têk çû. Ji kerema xwe dîsa biceribîne.'],
            ['keyword' => 'weWillSendAMailToTheEmailAddressYouRegisteredToRegainYourPassword', 'translated' => 'Em e-nameyek bişînin ser navnîşana e-nameyê ku te qeydkirî ye da ku şîfreyê xwe vegerî.'],
            ['keyword' => 'passwordResetEmailSent', 'translated' => 'E-nameya şîfreya nû vehatî bişînin.'],
            ['keyword' => 'anEmailHasBeenSentToYouFollowDirectionsInTheEmailToResetYourPassword', 'translated' => 'E-nameyek hat şandin we. Beramber rêzekan li e-nameyê şîfreyê xwe nû bike.'],
            ['keyword' => 'invalidCode', 'translated' => 'Koda nederbasdar'],
            ['keyword' => 'pleaseEnterThe4DigitOtpCode', 'translated' => 'Ji kerema xwe koda OTP ya 4 hejmarî binivîse'],
            ['keyword' => 'success', 'translated' => 'Serkeftin'],
            ['keyword' => 'otpVerifiedSuccessfully', 'translated' => 'OTP bi serketî hat pejirandin!'],
            ['keyword' => 'otpVerificationFailed', 'translated' => 'Pejirandina OTP têk çû'],
            ['keyword' => 'failedToVerifyOtpPleaseTryAgain', 'translated' => 'Pejirandina OTP têk çû. Ji kerema xwe dîsa biceribîne.'],
            ['keyword' => 'resendDisabled', 'translated' => 'Nûve şandin hat asteng kirin'],
            ['keyword' => 'pleaseWaitUntilTheTimerEndsToResendTheCode', 'translated' => 'Ji kerema xwe hinga ku demjimêr qedîm dibe bisekine da ku koda nûve bişînî.'],
            ['keyword' => 'verification', 'translated' => 'Pejirandin'],
            ['keyword' => 'passwordHasBeenSuccessfullyReset', 'translated' => 'Şîfre bi serketî nûvehat saz kirin.'],
            ['keyword' => 'passwordResetFailed', 'translated' => 'Nûve kirina şîfreyê têk çû'],
            ['keyword' => 'noResponseFromTheServerPleaseTryAgain', 'translated' => 'Ji serverê bersiv tune. Ji kerema xwe dîsa biceribîne.'],
            ['keyword' => 'somethingWentWrongPleaseTryAgainLater', 'translated' => 'Tiştek xelet çû. Ji kerema xwe paşê biceribîne.'],
            ['keyword' => 'createPassword', 'translated' => 'Şîfre çêbikin'],
            ['keyword' => 'chooseASecurePasswordThatWillBeEasyForYouToRemember', 'translated' => 'Şîfreyek ewle hilbijêre ku te bikar bi hêsanî bîbîne.'],
            ['keyword' => 'confirmYourPasswordHere', 'translated' => 'Li vir şîfreyê xwe piştrast bike']
        ];

        LanguageDetail::truncate();
        foreach ($languages as $language) {
            if ($language->code == 'ku') {
                foreach ($kurdishkeywords as $keyword) {
                    LanguageDetail::create([
                        'language_id' => $language->id,
                        'section_name' => 'Home Section',
                        'keyword' => $keyword['keyword'],
                        'translated' => $keyword['translated'],
                    ]);
                }
            } else {
                foreach ($homekeywords as $keyword) {
                    $translatedValue = ($language->code == 'en') ? $keyword['translated'] : '';
                    LanguageDetail::create([
                        'language_id' => $language->id,
                        'section_name' => 'Home Section',
                        'keyword' => $keyword['keyword'],
                        'translated' => $translatedValue,
                    ]);
                }
            }
        }
    }
}
