<?php

namespace App\Helpers;

use App\Models\LanguageDetail;
use Exception;
use Illuminate\Support\Str;

class LanguagesHelpers
{

    public static function languages_keywords($language_id, $code = null)
    {
        $homekeywords = [
            ['keyword' => 'languages', 'translated' => 'Languages', 'main_section' => 'Home Page', 'section_name' => 'Home Page Languages'],
            ['keyword' => 'privacyAndTerms', 'translated' => 'Privacy & Terms', 'main_section' => 'Home Page', 'section_name' => 'Home Page App Policy'],
            ['keyword' => 'signIn', 'translated' => 'Sign In', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'typeYourEmail', 'translated' => 'Type your E-Mail', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'typeYourPasswordHere', 'translated' => 'Type Your password Here', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'rememberMe', 'translated' => 'Remember Me', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'lostDevice', 'translated' => 'Lost Device', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'addNewDevice', 'translated' => 'Add New Device', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'password', 'translated' => 'Password', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'forgotPassword', 'translated' => 'Forgot Password', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'loginError', 'translated' => 'Login Error', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'theEmailAddressYouProvidedDoesNotCorrespondWithTheDeviceIdAssociatedWithTheAccount', 'translated' => 'The email address you provided does not correspond with the device ID associated with the account', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'newDevice', 'translated' => 'New Device', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'setupANewDevice', 'translated' => 'Setup a new device', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'emailVerification', 'translated' => 'Email Verification', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'send', 'translated' => 'Send', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'weWillSendAMailToTheEmailAddressWithACodeCheckSpamFolder', 'translated' => 'We will send a mail to the email address with a Code “Check Spam Folder”', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'emailSentTo', 'translated' => 'E-Mail sent to', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'codeVerification', 'translated' => 'Code Verification', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'anAuthenticationCodeHasBeenSentTo', 'translated' => 'An authentication code has been sent to', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'iDidntReceiveCode', 'translated' => "I didn't receive code?", 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'resendCode', 'translated' => 'Resend Code', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'secLeft', 'translated' => 'Sec left', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'verifyNow', 'translated' => 'Verify Now', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'changeDevice', 'translated' => 'Change Device', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'start', 'translated' => 'Start', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'connecting', 'translated' => 'Connecting', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'summary', 'translated' => 'Summary', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'status', 'translated' => 'Status', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'startNow', 'translated' => 'Start Now', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'yourNewDevice', 'translated' => 'Your new Device', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'yourOldDevice', 'translated' => 'Your Old Device', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'deviceId', 'translated' => 'Device ID', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'deviceRegistration', 'translated' => 'Device Registration', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'disconnectOldDevice', 'translated' => 'Disconnect old Device', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'takeMeToSignIn', 'translated' => 'Take me to Sign in', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'close', 'translated' => 'Close', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign In'],
            ['keyword' => 'selectGender', 'translated' => 'Select Gender', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'imFemale', 'translated' => "I'm Female", 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'imMale', 'translated' => "I'm Male", 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'back', 'translated' => 'Back', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'next', 'translated' => 'Next', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'error', 'translated' => 'Error', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'failedToGetCurrentLocationPleaseMakeSureLocationServicesAreEnabled', 'translated' => 'Failed to get current location. Please make sure location services are enabled.', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'pleaseEnterAnAddressBeforeProceeding', 'translated' => 'Please enter an address before proceeding.', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'selectCountry', 'translated' => 'Select Country', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'currentLocation', 'translated' => 'Current location', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'yourLocation', 'translated' => 'Your Location', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'yourCurrentLocation', 'translated' => 'Your current location', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'cameraNotAvailable', 'translated' => 'Camera not available', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'aboutYou', 'translated' => 'About You', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'yourFirstname', 'translated' => 'Your Firstname', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'yourLastname', 'translated' => 'Your Lastname', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'yourUsername', 'translated' => 'Your Username', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'anErrorOccurredWhileSubmittingTheFormPleaseTryAgainLater', 'translated' => 'An error occurred while submitting the form. Please try again later.', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'anUnknownErrorOccurred', 'translated' => 'An unknown error occurred', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'step', 'translated' => 'Step', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'yourStatus', 'translated' => 'Your Status', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'single', 'translated' => 'Single', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'engaged', 'translated' => 'Engaged', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'married', 'translated' => 'Married', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'yourBirthday', 'translated' => 'Your Birthday', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'information', 'translated' => 'Information', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'uMustBeAtLeast16YearOld', 'translated' => 'You must be at least 16 years old', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'confirm', 'translated' => 'Confirm', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'yourOrigin', 'translated' => 'Your Origin', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'pleaseSelect', 'translated' => 'Please Select', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'imKurdish', 'translated' => "I'm Kurdish", 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'imNotKurdish', 'translated' => "I'm not Kurdish", 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'selectYourProvince', 'translated' => 'Select your Province', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'selectYourCity', 'translated' => 'Select your City', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'kurdistan', 'translated' => 'Kurdistan', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'yourEmailAddress', 'translated' => 'Your E-Mail Address', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'emailAddress', 'translated' => 'E-Mail Address', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'enterYourEmail', 'translated' => 'Enter Your E-Mail', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'repeatYourEmail', 'translated' => 'Repeat your E-Mail', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'confirmYourEmail', 'translated' => 'Confirm Your E-Mail', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'thisEmailAlreadyExists', 'translated' => 'This E-Mail already exists', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'loginNow', 'translated' => 'Login now', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'emailDoesntMatch', 'translated' => "E-Mail doesn't match", 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'yourPhoneNumber', 'translated' => 'Your Phone Number', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'typeYourNumber', 'translated' => 'Type your number', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'createAPassword', 'translated' => 'Create a Password', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'enterAPassword', 'translated' => 'Enter a Password', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'repeatAPassword', 'translated' => 'Repeat a Password', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'rewriteYourPassword', 'translated' => 'Rewrite your password', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'hasAtLeast810Characters', 'translated' => 'Has at least 8-10 Characters', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'hasAnUppercaseLetterOrSymbol', 'translated' => 'Has an uppercase letter or symbol', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'hasANumbers', 'translated' => 'Has a number', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'hasPasswordMatched', 'translated' => 'Has password matched', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'acceptPolicyAndTerms', 'translated' => 'Accept policy and terms', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'tüBexirHatiUserName', 'translated' => 'Tü Bexir Hati User Name', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'fromLocation', 'translated' => 'From location', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'kurdistanRojava10111Qamishlo', 'translated' => 'Kurdistan - Rojava - 10111 Qamishlo', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'completeYourAccount', 'translated' => 'Complete your Account', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'accountConfirmation', 'translated' => 'Account Confirmation', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'anEmailHasBeenSentToYouFollowDirectionInTheEmailToConfirmYourAccount', 'translated' => 'An e-mail has been sent to you. Follow the directions in the e-mail to confirm your Account', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'pleaseEnterTheOtpCodeYouReceivedThroughEmail', 'translated' => 'Please enter the OTP code you received through email.', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'accountConfirmedSuccessfully', 'translated' => 'Account confirmed successfully!', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'unexpectedResponseFromTheServerPleaseTryAgainLater', 'translated' => 'Unexpected response from the server. Please try again later.', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'anErrorOccurredWhileProcessingYourRequest', 'translated' => 'An error occurred while processing your request.', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'noResponseFromServerPleaseCheckYourInternetConnection', 'translated' => 'No response from the server. Please check your internet connection.', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'anUnexpectedErrorOccurredPleaseTryAgainLater', 'translated' => 'An unexpected error occurred. Please try again later.', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'confirmYourAccount', 'translated' => 'Confirm your Account', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'weWillSendAMailToTheEmailAddressYouRegisteredToActivateYourAccount', 'translated' => 'We will send a mail to the e-mail address you registered to activate your Account', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'didntReceiveCode', 'translated' => "Didn't receive code?", 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'resentNow', 'translated' => 'Resent Now', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'accountCreated', 'translated' => 'Account Created!', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'yourAccountHadBeedCreatedSuccessfully', 'translated' => 'Your account had been created successfully.', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'pleaseSignInToUseYourAccountAndEnjoy', 'translated' => 'Please sign in to use your account and enjoy', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],


            ['keyword' => 'search', 'translated' => 'Search', 'main_section' => 'Home Page', 'section_name' => 'Home Page Landing Page'],
       //landing page
            ['keyword' => 'Advertisment', 'translated' => 'Advertisment', 'main_section' => 'Settings', 'section_name' => 'Home Page Landing Page'],
            ['keyword' => 'Latest Feeds', 'translated' => 'Latest Feeds', 'main_section' => 'Settings', 'section_name' => 'Home Page Landing Page'],
            ['keyword' => 'Username', 'translated' => 'Username', 'main_section' => 'Settings', 'section_name' => 'Home Page Landing Page'],
            ['keyword' => 'justnow', 'translated' => 'justnow', 'main_section' => 'Settings', 'section_name' => 'Home Page Landing Page'],
            ['keyword' => 'some text will be here', 'translated' => 'some text will be here', 'main_section' => 'Settings', 'section_name' => 'Home Page Landing Page'],
            ['keyword' => 'Add a commment here', 'translated' => 'some text will be here', 'main_section' => 'Settings', 'section_name' => 'Home Page Landing Page'],     
            
            //end landing page












            ['keyword' => 'createAccountError', 'translated' => 'Create Account Error', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'thisDeviceIsAlreadyLinkedToAnExistingAccountCreatingANewAccountIsNotPossibleYouHaveTheFollowingOptions:', 'translated' => 'This device is already linked to an existing account. Creating a new account is not possible. You have the following options:', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'mailAndPasswordNeedIt', 'translated' => 'Mail & Password need it', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
            ['keyword' => 'eMailNeedIt', 'translated' => 'E-Mail need it', 'main_section' => 'Home Page', 'section_name' => 'Home Page Sign Up'],
        ];

        $kurdishkeywords = [
            ['translated' => 'Ziman'],
            ['translated' => 'Nepênî û Merc'],
            ['translated' => 'Têkevin'],
            ['translated' => 'E-nameya xwe binivîse'],
            ['translated' => 'Şîfreya xwe li vir binivîse'],
            ['translated' => 'Min Bîne Bîra Xwe'],
            ['translated' => 'Amûra Wenda'],
            ['translated' => 'Amûrek Nû Zêde Bike'],
            ['translated' => 'Şîfre'],
            ['translated' => 'Şîfre Ji Bîr Kir'],
            ['translated' => 'Çewtiya Têketinê'],
            ['translated' => 'Navnîşana e-nameya ku we peyda kiriye bi nasnameya cîhaza ku bi hesabê ve girêdayî ye re têkildar nabe'],
            ['translated' => 'Amûra Nû'],
            ['translated' => 'Amûrek nû saz bike'],
            ['translated' => 'Verastkirina E-nameyê'],
            ['translated' => 'Bişîne'],
            ['translated' => 'Em ê e-nameyek bi kodek ji navnîşana e-nameyê re bişînin "Pelê Spam Kontrol Bikin"'],
            ['translated' => 'E-name ji bo şandin'],
            ['translated' => 'Verastkirina Kodê'],
            ['translated' => 'Kodek rastnivîsandinê ji bo hate şandin'],
            ['translated' => 'Min kod nestand?'],
            ['translated' => 'Kodê Ji Nû Ve Bişîne'],
            ['translated' => 'Çirk çûn'],
            ['translated' => 'Niha Verast Bike'],
            ['translated' => 'Amûrê Biguherîne'],
            ['translated' => 'Destpêk'],
            ['translated' => 'Girêdan'],
            ['translated' => 'Kurte'],
            ['translated' => 'Rewş'],
            ['translated' => 'Niha Dest Pê Bike'],
            ['translated' => 'Amûra weya nû'],
            ['translated' => 'Amûra weya kevn'],
            ['translated' => 'Nasnameya Amûrê'],
            ['translated' => 'Qeydkirina Amûrê'],
            ['translated' => 'Amûra kevn qut bike'],
            ['translated' => 'Min Bibe Têketinê'],
            ['translated' => 'Bigire'],
            ['translated' => 'Zayend Hilbijêre'],
            ['translated' => 'Ez Jinim'],
            ['translated' => 'Ez Nêrim'],
            ['translated' => 'Paş'],
            ['translated' => 'Piştî'],
            ['translated' => 'Çewtî'],
            ['translated' => 'Bi destxistina cîhê heyî biser neket. Ji kerema xwe pê ewle bine ku karûbarên cîhê çalak in.'],
            ['translated' => 'Ji kerema xwe berî ku hûn bidomînin navnîşek binivîsin.'],
            ['translated' => 'Welat Hilbijêre'],
            ['translated' => 'Cihê niha'],
            ['translated' => 'Cihê we'],
            ['translated' => 'Cihê weya niha'],
            ['translated' => 'Kamera ne berdest e'],
            ['translated' => 'Derbarê We'],
            ['translated' => 'Navê We'],
            ['translated' => 'Paşnavê We'],
            ['translated' => 'Navê Bikarhênerê We'],
            ['translated' => 'Di dema şandina formê de çewtiyek çêbû. Ji kerema xwe paşê dîsa biceribînin.'],
            ['translated' => 'Çewtiyek nenas çêbû'],
            ['translated' => 'Gav'],
            ['translated' => 'Rewşa We'],
            ['translated' => 'Yekane'],
            ['translated' => 'Nişanî'],
            ['translated' => 'Zewicî'],
            ['translated' => 'Rojbûna We'],
            ['translated' => 'Agahî'],
            ['translated' => 'Divê hûn herî kêm 16 salî bin'],
            ['translated' => 'Erêkirin'],
            ['translated' => 'Esilê We'],
            ['translated' => 'Ji Kerema Xwe Hilbijêrin'],
            ['translated' => 'Ez Kurdim'],
            ['translated' => 'Ez Ne Kurdim'],
            ['translated' => 'Parêzgeha Xwe Hilbijêrin'],
            ['translated' => 'Bajarê Xwe Hilbijêrin'],
            ['translated' => 'Kurdistan'],
            ['translated' => 'Navnîşana E-nameya We'],
            ['translated' => 'Navnîşana E-nameyê'],
            ['translated' => 'E-nameya Xwe Binivîse'],
            ['translated' => 'E-nameya Xwe Dubare Bike'],
            ['translated' => 'E-nameya Xwe Erê Bike'],
            ['translated' => 'Ev E-name jixwe heye'],
            ['translated' => 'Niha Têkeve'],
            ['translated' => 'E-name li hev nake'],
            ['translated' => 'Hejmara Telefona We'],
            ['translated' => 'Hejmara xwe binivîse'],
            ['translated' => 'Şîfreyek Biafirîne'],
            ['translated' => 'Şîfreyek binivîse'],
            ['translated' => 'Şîfreyek dubare bike'],
            ['translated' => 'Şîfreya xwe ji nû ve binivîse'],
            ['translated' => 'Bi kêmanî 8-10 tîpan heye'],
            ['translated' => 'Tîpek mezin an sembolek heye'],
            ['translated' => 'Hejmarek heye'],
            ['translated' => 'Şîfre li hev kir'],
            ['translated' => 'Siyaseta û mercan qebûl bike'],
            ['translated' => 'Navê Bikarhêner Tü Bexir Hati'],
            ['translated' => 'Ji cîh'],
            ['translated' => 'Kurdistan - Rojava - 10111 Qamişlo'],
            ['translated' => 'Hesaba xwe temam bike'],
            ['translated' => 'Tesdîqkirina Hesabê'],
            ['translated' => 'E-nameyek ji we re hatiye şandin. Ji bo tesdîqkirina Hesabê xwe rêwerzên di e-nameyê de bişopînin'],
            ['translated' => 'Ji kerema xwe koda OTP-ê ya ku we bi e-nameyê wergirtiye binivîsin.'],
            ['translated' => 'Hesab bi serkeftî hate tesdîqkirin!'],
            ['translated' => 'Ji serverê bersivek nediyar hat. Ji kerema xwe paşê dîsa biceribînin.'],
            ['translated' => 'Di dema pêvajoykirina daxwaza we de çewtiyek çêbû.'],
            ['translated' => 'Ji serverê tu bersiv tune. Ji kerema xwe pêwendiya xweya înternetê kontrol bikin.'],
            ['translated' => 'Çewtiyek nediyar çêbû. Ji kerema xwe paşê dîsa biceribînin.'],
            ['translated' => 'Hesaba xwe tesdîq bike'],
            ['translated' => 'Em ê e-nameyek ji navnîşana e-nameya ku we qeyd kiriye bişînin da ku Hesaba we çalak bikin'],
            ['translated' => 'Kod negihaşt?'],
            ['translated' => 'Niha Ji Nû Ve Hate Şandin'],
            ['translated' => 'Hesab Hate Afirandin!'],
            ['translated' => 'Hesaba we bi serkeftî hate afirandin.'],
            ['translated' => 'Ji kerema xwe têkevin da ku hûn hesaba xwe bikar bînin û kêfê bikin'],
            ['translated' => 'Lêgerîn'],
            ['translated' => 'Navê xwe binivîse'],
            ['translated' => 'Paşnavê xwe binivîse'],
            ['translated' => 'Navê bikarhênerê xwe binivîse'],
            ['translated' => 'Rêzokê qebûl bike û'],
            ['translated' => 'Merc'],
            ['translated' => 'Ji kerema xwe e-nameya rast binivîse.'],
            ['translated' => 'Ji nû ve saz kirina amûrê têk çû. Ji kerema xwe dîsa biceribîne.'],
            ['translated' => 'Em e-nameyek bişînin ser navnîşana e-nameyê ku te qeydkirî ye da ku şîfreyê xwe vegerî.'],
            ['translated' => 'E-nameya şîfreya nû vehatî bişînin.'],
            ['translated' => 'E-nameyek hat şandin we. Beramber rêzekan li e-nameyê şîfreyê xwe nû bike.'],
            ['translated' => 'Koda nederbasdar'],
            ['translated' => 'Ji kerema xwe koda OTP ya 4 hejmarî binivîse'],
            ['translated' => 'Serkeftin'],
            ['translated' => 'OTP bi serketî hat pejirandin!'],
            ['translated' => 'Pejirandina OTP têk çû'],
            ['translated' => 'Pejirandina OTP têk çû. Ji kerema xwe dîsa biceribîne.'],
            ['translated' => 'Nûve şandin hat asteng kirin'],
            ['translated' => 'Ji kerema xwe hinga ku demjimêr qedîm dibe bisekine da ku koda nûve bişînî.'],
            ['translated' => 'Pejirandin'],
            ['translated' => 'Şîfre bi serketî nûvehat saz kirin.'],
            ['translated' => 'Nûve kirina şîfreyê têk çû'],
            ['translated' => 'Ji serverê bersiv tune. Ji kerema xwe dîsa biceribîne.'],
            ['translated' => 'Tiştek xelet çû. Ji kerema xwe paşê biceribîne.'],
            ['translated' => 'Şîfre çêbikin'],
            ['translated' => 'Şîfreyek ewle hilbijêre ku te bikar bi hêsanî bîbîne.'],
            ['translated' => 'Li vir şîfreyê xwe piştrast bike'],
            ['translated' => 'Çewtiya Hesabê Biafirîne'],
            ['translated' => 'Ev cîhaz jixwe bi hesabek heyî ve girêdayî ye. Çêkirina hesabek nû ne mimkûn e. Vebijarkên we yên jêrîn hene:'],
            ['translated' => 'Mail & Şîfre hewce dike'],
            ['translated' => 'E-Mail hewce dike'],
        ];

        // Validate that the arrays match in length
        if (count($homekeywords) !== count($kurdishkeywords)) {
            throw new Exception('Keyword arrays do not match in length.');
        }

        try {
            foreach ($homekeywords as $key => $keyword) {
                $translated = $code === 'ku' ? $kurdishkeywords[$key]['translated'] : $keyword['translated'];

                LanguageDetail::create([
                    'language_id' => $language_id,
                    'section_name' => $keyword['section_name'],
                    'main_section' => $keyword['main_section'],
                    'keyword' => $keyword['keyword'],
                    'translated' => $translated ?? '',
                ]);
            }
            return 'success';
        } catch (\Exception $e) {
            // Log or handle errors if necessary
            return 'Error: ' . $e->getMessage();
        }
    }

    public static function languages_settings_keywords($language_id, $code = null)
    {
        $homekeywords = [
            ['keyword' => 'settingsOverview', 'translated' => 'Settings Overview', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'accountStatus', 'translated' => 'Account Status', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'information', 'translated' => 'Information', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'accountIsActive', 'translated' => 'Account is Active', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'accountIsInactive', 'translated' => 'Account is Inactive', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'fastAccess', 'translated' => 'Fast Access', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'setting', 'translated' => 'Setting', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'appSettings', 'translated' => 'App Settings', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'office', 'translated' => 'Office', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'myOffice', 'translated' => 'My Office', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'notifications', 'translated' => 'Notifications', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'profile', 'translated' => 'Profile', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'appProfile', 'translated' => 'App Profile', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'fastSetting', 'translated' => 'Fast Setting', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'bazar', 'translated' => 'Bazar', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'privacy', 'translated' => 'Privacy', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'orders', 'translated' => 'Orders', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'password', 'translated' => 'Password', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'playMusic', 'translated' => 'Play Music', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'ringtone', 'translated' => 'RingTone', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'ads', 'translated' => 'Ads', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'email', 'translated' => 'E-mail', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'manageMyItems', 'translated' => 'Manage my Items', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'manageMyProfile', 'translated' => 'Manage My Profile', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'managePassword', 'translated' => 'Manage Password', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'managePlayer', 'translated' => 'Manage Player', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'manageRingtone', 'translated' => 'Manage Ringtone', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'manageMyAds', 'translated' => 'Manage My Ads', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'manageEmail', 'translated' => 'Manage E-Mail', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'myChannels', 'translated' => 'My Channels', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'myStorage', 'translated' => 'My Storage', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'used', 'translated' => 'Used', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'storage', 'translated' => 'Storage', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'images', 'translated' => 'Images', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'videos', 'translated' => 'Videos', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'yekbunSupport', 'translated' => 'Yekbun Support', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'yekbun', 'translated' => 'Yekbun', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'appPolicy', 'translated' => 'App Policy', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'contacts', 'translated' => 'Contacts', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'aboutUs', 'translated' => 'About Us', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'currently', 'translated' => 'Currently', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'upgradeTo', 'translated' => 'Upgrade to', 'main_section' => 'Settings', 'section_name' => 'Settings Overview'],
            ['keyword' => 'profileSettings', 'translated' => 'Profile Settings', 'main_section' => 'Settings', 'section_name' => 'App Settings'],
            ['keyword' => 'myAccount', 'translated' => 'My Account', 'main_section' => 'Settings', 'section_name' => 'App Settings'],
            ['keyword' => 'manageMyAccounts', 'translated' => 'Manage My Accounts', 'main_section' => 'Settings', 'section_name' => 'App Settings'],
            ['keyword' => 'myPrivacy', 'translated' => 'My Privacy', 'main_section' => 'Settings', 'section_name' => 'App Settings'],
            ['keyword' => 'manageMyPrivacy', 'translated' => 'Manage My Privacy', 'main_section' => 'Settings', 'section_name' => 'App Settings'],
            ['keyword' => 'myNotifications', 'translated' => 'My Notifications', 'main_section' => 'Settings', 'section_name' => 'App Settings'],
            ['keyword' => 'manageNotificationAndRingtone', 'translated' => 'Manage Notification & Ringtone', 'main_section' => 'Settings', 'section_name' => 'App Settings'],
            ['keyword' => 'myNetwork', 'translated' => 'My Network', 'main_section' => 'Settings', 'section_name' => 'App Settings'],
            ['keyword' => 'manageTheConnections', 'translated' => 'Manage the Connections', 'main_section' => 'Settings', 'section_name' => 'App Settings'],
            ['keyword' => 'myStorage', 'translated' => 'My Storage', 'main_section' => 'Settings', 'section_name' => 'App Settings'],
            ['keyword' => 'manageTheStorage', 'translated' => 'Manage the Storage', 'main_section' => 'Settings', 'section_name' => 'App Settings'],
            ['keyword' => 'newViolate', 'translated' => 'New Violate', 'main_section' => 'Settings', 'section_name' => 'App Profile'],
            ['keyword' => 'wereNotAllowedBadFeedsOnPlatform', 'translated' => 'We re not Allowed Bad Feeds on Platform', 'main_section' => 'Settings', 'section_name' => 'App Profile'],
            ['keyword' => 'latestFeeds', 'translated' => 'Latest Feeds', 'main_section' => 'Settings', 'section_name' => 'App Profile'],
            ['keyword' => 'seeAll', 'translated' => 'See All', 'main_section' => 'Settings', 'section_name' => 'App Profile'],
            ['keyword' => 'addACommentHere', 'translated' => 'Add a Comment Here', 'main_section' => 'Settings', 'section_name' => 'App Profile'],
            ['keyword' => 'myPhotos', 'translated' => 'My Photos', 'main_section' => 'Settings', 'section_name' => 'App Profile'],
            ['keyword' => 'myVideos', 'translated' => 'My Videos', 'main_section' => 'Settings', 'section_name' => 'App Profile'],
            ['keyword' => 'latestReels', 'translated' => 'Latest Reels', 'main_section' => 'Settings', 'section_name' => 'App Profile'],
            ['keyword' => 'wishesAndThanks', 'translated' => 'Wishes & Thanks', 'main_section' => 'Settings', 'section_name' => 'App Profile'],
            ['keyword' => 'latestStories', 'translated' => 'Latest Stories', 'main_section' => 'Settings', 'section_name' => 'App Profile'],

// my account
            ['keyword' => 'My account', 'translated' => 'My account', 'main_section' => 'Settings', 'section_name' => 'My Account'],
            ['keyword' => 'User Name', 'translated' => 'User Name', 'main_section' => 'Settings', 'section_name' => 'My Account'],
            ['keyword' => 'My Information', 'translated' => 'My Information', 'main_section' => 'Settings', 'section_name' => 'My Account'],
            ['keyword' => 'Nick Name', 'translated' => 'Nick Name', 'main_section' => 'Settings', 'section_name' => 'My Account'],
            ['keyword' => 'Status', 'translated' => 'Status', 'main_section' => 'Settings', 'section_name' => 'My Account'],
            ['keyword' => 'My Email', 'translated' => 'My Email', 'main_section' => 'Settings', 'section_name' => 'My Account'],
            ['keyword' => 'Manage Email', 'translated' => 'Manage Email', 'main_section' => 'Settings', 'section_name' => 'My Account'],
            ['keyword' => 'My Password', 'translated' => 'My Password', 'main_section' => 'Settings', 'section_name' => 'My Account'],
            ['keyword' => 'Manage My Password', 'translated' => 'Manage My Password', 'main_section' => 'Settings', 'section_name' => 'My Account'],
            ['keyword' => ' My Residence', 'translated' => 'My Residence', 'main_section' => 'Settings', 'section_name' => 'My Account'],
            ['keyword' => ' My Living and birth location', 'translated' => 'My Living and birth location', 'main_section' => 'Settings', 'section_name' => 'My Account'],
            ['keyword' => ' My Profile', 'translated' => 'My Profile', 'main_section' => 'Settings', 'section_name' => 'My Account'],
            ['keyword' => ' Close My Profile', 'translated' => ' Close My Profile', 'main_section' => 'Settings', 'section_name' => 'My Account'],
            ['keyword' => 'Yekbun Support', 'translated' => ' Yekbun Support', 'main_section' => 'Settings', 'section_name' => 'My Account'],
            ['keyword' => 'Yekbun Terms', 'translated' => ' Yekbun Terms', 'main_section' => 'Settings', 'section_name' => 'My Account'],
            ['keyword' => 'Yekbun Contacts', 'translated' => ' Yekbun Contacts', 'main_section' => 'Settings', 'section_name' => 'My Account'],
            ['keyword' => 'Yekbun About us', 'translated' => ' Yekbun About us', 'main_section' => 'Settings', 'section_name' => 'My Account'],


            // My account information
            ['keyword' => 'My Account INformation', 'translated' => ' My Account INformation', 'main_section' => 'Settings', 'section_name' => 'My Account Information'],
            ['keyword' => 'Profile Setting', 'translated' => 'Profile Setting', 'main_section' => 'Settings', 'section_name' => 'My Account Information'],
            ['keyword' => 'Edit my nick name', 'translated' => 'Edit my nick name', 'main_section' => 'Settings', 'section_name' => 'My Account Information'],
            ['keyword' => 'Edit my nick name', 'translated' => 'Edit my nick name', 'main_section' => 'Settings', 'section_name' => 'My Account Information'],
            ['keyword' => 'Information', 'translated' => 'Information', 'main_section' => 'Settings', 'section_name' => 'My Account Information'],
            ['keyword' => 'Status Setting', 'translated' => 'Status Setting', 'main_section' => 'Settings', 'section_name' => 'My Account Information'],
            ['keyword' => 'Single', 'translated' => 'Single', 'main_section' => 'Settings', 'section_name' => 'My Account Information'],
            ['keyword' => 'Engagment', 'translated' => 'Engagment', 'main_section' => 'Settings', 'section_name' => 'My Account Information'],
            ['keyword' => 'Married', 'translated' => 'Married', 'main_section' => 'Settings', 'section_name' => 'My Account Information'],
            ['keyword' => 'Save', 'translated' => 'Save', 'main_section' => 'Settings', 'section_name' => 'My Account Information'],

   // My account Email

             ['keyword' => 'My Account - My  Email', 'translated' => 'My Account - My  Email', 'main_section' => 'Settings', 'section_name' => 'My Account My Email'],
             ['keyword' => 'Your Current Email', 'translated' => 'Your Current Email', 'main_section' => 'Settings', 'section_name' => 'My Account My Email'],
             ['keyword' => 'Email setting', 'translated' => 'Email setting', 'main_section' => 'Settings', 'section_name' => 'My Account My Email'],
             ['keyword' => 'Your Old Email', 'translated' => 'Your Old Email', 'main_section' => 'Settings', 'section_name' => 'My Account My Email'],
             ['keyword' => 'Your new Email', 'translated' => 'Your new Email', 'main_section' => 'Settings', 'section_name' => 'My Account My Email'],
             ['keyword' => 'type your Email here', 'translated' => 'Your new Email', 'main_section' => 'Settings', 'section_name' => 'My Account My Email'],
             ['keyword' => 'Repeat new Email', 'translated' => 'Repeat new Email', 'main_section' => 'Settings', 'section_name' => 'My Account My Email'],
             ['keyword' => 'type your Email here', 'translated' => 'Your new Email', 'main_section' => 'Settings', 'section_name' => 'My Account My Email'],
             ['keyword' => 'Submit', 'translated' => 'Submit', 'main_section' => 'Settings', 'section_name' => 'My Account My Email'],
             ['keyword' => 'An Authentication code has been sent to', 'translated' => 'An Authentication code has been sent to', 'main_section' => 'Settings', 'section_name' => 'My Account My Email'],
             ['keyword' => 'I didnot received the code', 'translated' => 'I didnot received the code', 'main_section' => 'Settings', 'section_name' => 'My Account My Email'],
             ['keyword' => 'Resend Code', 'translated' => 'Resend Code', 'main_section' => 'Settings', 'section_name' => 'My Account My Email'],
             ['keyword' => 'Verify now', 'translated' => 'Verify now', 'main_section' => 'Settings', 'section_name' => 'My Account My Email'],
   // My account Email
             ['keyword' => 'My Account - My password', 'translated' => 'My Account - My password', 'main_section' => 'Settings', 'section_name' => 'My Account My Password'],
             ['keyword' => 'Password Setting', 'translated' => 'Password Setting', 'main_section' => 'Settings', 'section_name' => 'My Account My Password'],
             ['keyword' => 'Your Old Password', 'translated' => 'Your Old Password', 'main_section' => 'Settings', 'section_name' => 'My Account My Password'],
             ['keyword' => 'Password will be visible here', 'translated' => 'Password will be visible here', 'main_section' => 'Settings', 'section_name' => 'My Account My Password'],
             ['keyword' => 'New  Password', 'translated' => 'New  Password', 'main_section' => 'Settings', 'section_name' => 'My Account My Password'],
             ['keyword' => 'has atleast 8-10 characters  ', 'translated' => 'has atleast 8-10 characters', 'main_section' => 'Settings', 'section_name' => 'My Account My Password'],
             ['keyword' => 'has an upper case or lower  ', 'translated' => 'has an upper case or lower', 'main_section' => 'Settings', 'section_name' => 'My Account My Password'],
             ['keyword' => 'has a numbers ', 'translated' => 'has a numbers', 'main_section' => 'Settings', 'section_name' => 'My Account My Password'],
             ['keyword' => 'Continue ', 'translated' => 'Continue', 'main_section' => 'Settings', 'section_name' => 'My Account My Password'],
  // My account Resedence

            ['keyword' => 'My Account - My Residence', 'translated' => 'My Account - My Residence', 'main_section' => 'Settings', 'section_name' => 'My Account My Residence'],
            ['keyword' => ' Residence', 'translated' => 'Residence', 'main_section' => 'Settings', 'section_name' => 'My Account My Residence'],
            ['keyword' => ' state zip code,city', 'translated' => 'state zip code,city', 'main_section' => 'Settings', 'section_name' => 'My Account My Residence'],
            ['keyword' => ' Change your location here', 'translated' => 'Change your location here', 'main_section' => 'Settings', 'section_name' => 'My Account My Residence'],
            ['keyword' => 'Select  country ', 'translated' => 'Change your location here', 'main_section' => 'Settings', 'section_name' => 'My Account My Residence'],
            ['keyword' => 'Search  ', 'translated' => 'Search', 'main_section' => 'Settings', 'section_name' => 'My Account My Residence'],

//setting privacy

            ['keyword' => 'setting privacy', 'translated' => 'setting privacy', 'main_section' => 'Settings', 'section_name' => 'Setting Privacy'],
            ['keyword' => 'my profile image', 'translated' => 'my profile image', 'main_section' => 'Settings', 'section_name' => 'Setting Privacy'],
            ['keyword' => 'profile image privacy', 'translated' => 'profile image privacy', 'main_section' => 'Settings', 'section_name' => 'Setting Privacy'],
            ['keyword' => 'for public', 'translated' => 'for public', 'main_section' => 'Settings', 'section_name' => 'Setting Privacy'],
            ['keyword' => 'Friends only', 'translated' => 'Friends only', 'main_section' => 'Settings', 'section_name' => 'Setting Privacy'],
            ['keyword' => 'family only', 'translated' => 'family only', 'main_section' => 'Settings', 'section_name' => 'Setting Privacy'],
            ['keyword' => 'Everyone can see', 'translated' => 'Everyone can see', 'main_section' => 'Settings', 'section_name' => 'Setting Privacy'],
            ['keyword' => 'Contact permission', 'translated' => 'Contact permission', 'main_section' => 'Settings', 'section_name' => 'Setting Privacy'],
            ['keyword' => 'privacy setting', 'translated' => 'privacy setting', 'main_section' => 'Settings', 'section_name' => 'Setting Privacy'],
            ['keyword' => 'user request', 'translated' => 'user request', 'main_section' => 'Settings', 'section_name' => 'Setting Privacy'],
            ['keyword' => 'Get greeting', 'translated' => 'Get greeting ', 'main_section' => 'Settings', 'section_name' => 'Setting Privacy'],
            ['keyword' => 'recived friend request ', 'translated' => 'recived friend request', 'main_section' => 'Settings', 'section_name' => 'Setting Privacy'],
            ['keyword' => 'recived user greeting', 'translated' => 'recived user greeting', 'main_section' => 'Settings', 'section_name' => 'Setting Privacy'],
            ['keyword' => 'Visiblities', 'translated' => 'Visiblities', 'main_section' => 'Settings', 'section_name' => 'Setting Privacy'],
            ['keyword' => 'List me in Search', 'translated' => 'List me in Search', 'main_section' => 'Settings', 'section_name' => 'Setting Privacy'],

             //setting Notification

            ['keyword' => 'Setting Notification', 'translated' => 'Setting Notification', 'main_section' => 'Settings', 'section_name' => 'Setting Notification'],
            ['keyword' => 'Notification', 'translated' => 'Notification', 'main_section' => 'Settings', 'section_name' => 'Setting Notification'],
            ['keyword' => 'calls', 'translated' => 'calls', 'main_section' => 'Settings', 'section_name' => 'Setting Notification'],
            ['keyword' => 'message', 'translated' => 'message', 'main_section' => 'Settings', 'section_name' => 'Setting Notification'],
            ['keyword' => 'Ringtone', 'translated' => 'Ringtone', 'main_section' => 'Settings', 'section_name' => 'Setting Notification'],
            ['keyword' => 'Admin Feed', 'translated' => 'Admin Feed', 'main_section' => 'Settings', 'section_name' => 'Setting Notification'],
            ['keyword' => 'New Music', 'translated' => 'New Music', 'main_section' => 'Settings', 'section_name' => 'Setting Notification'],
            ['keyword' => 'New history', 'translated' => 'New history', 'main_section' => 'Settings', 'section_name' => 'Setting Notification'],
            ['keyword' => 'New votes', 'translated' => 'New votes', 'main_section' => 'Settings', 'section_name' => 'Setting Notification'],
            ['keyword' => 'New videos', 'translated' => 'New videos', 'main_section' => 'Settings', 'section_name' => 'Setting Notification'],
            ['keyword' => 'New events', 'translated' => 'New events', 'main_section' => 'Settings', 'section_name' => 'Setting Notification'],
            ['keyword' => 'New Donation', 'translated' => 'New Donation', 'main_section' => 'Settings', 'section_name' => 'Setting Notification'],
            ['keyword' => 'New clips', 'translated' => 'New clips', 'main_section' => 'Settings', 'section_name' => 'Setting Notification'],
            ['keyword' => 'New wishes', 'translated' => 'New wishes', 'main_section' => 'Settings', 'section_name' => 'Setting Notification'],
            ['keyword' => 'New emotions', 'translated' => 'New emotions', 'main_section' => 'Settings', 'section_name' => 'Setting Notification'],
            ['keyword' => 'Info Banner', 'translated' => 'Info Banner', 'main_section' => 'Settings', 'section_name' => 'Setting Notification'],
            ['keyword' => 'None', 'translated' => 'None', 'main_section' => 'Settings', 'section_name' => 'Setting Notification'],
            ['keyword' => 'Banner', 'translated' => 'Banner', 'main_section' => 'Settings', 'section_name' => 'Setting Notification'],
            ['keyword' => 'Alert', 'translated' => 'Alert', 'main_section' => 'Settings', 'section_name' => 'Setting Notification'],

//Manage Ringtone
            ['keyword' => 'Manage Ringtone', 'translated' => 'Manage Ringtone', 'main_section' => 'Settings', 'section_name' => 'Manage Ringtone'],
            ['keyword' => 'select Ringtone ', 'translated' => 'select Ringtone', 'main_section' => 'Settings', 'section_name' => 'Manage Ringtone'],
            ['keyword' => 'save & close', 'translated' => 'save & close', 'main_section' => 'Settings', 'section_name' => 'Manage Ringtone'],

//Setting my network
          ['keyword' => 'Setting My Network', 'translated' => 'Setting My Network', 'main_section' => 'Settings', 'section_name' => 'Setting My Network'],
          ['keyword' => 'Network', 'translated' => 'Network', 'main_section' => 'Settings', 'section_name' => 'Setting My Network'],
          ['keyword' => 'Live Stream', 'translated' => 'Live Stream', 'main_section' => 'Settings', 'section_name' => 'Setting My Network'],
          ['keyword' => 'Play Music', 'translated' => 'Play Music', 'main_section' => 'Settings', 'section_name' => 'Setting My Network'],
          ['keyword' => 'Play Video', 'translated' => 'Play Video', 'main_section' => 'Settings', 'section_name' => 'Setting My Network'],
          ['keyword' => 'Audio Call', 'translated' => 'Audio Call', 'main_section' => 'Settings', 'section_name' => 'Setting My Network'],
          ['keyword' => 'Interview', 'translated' => 'Interview', 'main_section' => 'Settings', 'section_name' => 'Setting My Network'],
          ['keyword' => 'wifi 5g', 'translated' => 'wifi 5g', 'main_section' => 'Settings', 'section_name' => 'Setting My Network'],
//Setting my storage
        ['keyword' => 'Setting My Storage', 'translated' => 'Setting My Storage', 'main_section' => 'Settings', 'section_name' => 'Setting My Storage'],
        ['keyword' => 'yekbun  Storage', 'translated' => 'yekbun  Storage', 'main_section' => 'Settings', 'section_name' => 'Setting My Storage'],
        ['keyword' => 'In development will be avaialble soon', 'translated' => 'In development will be avaialble soon', 'main_section' => 'Settings', 'section_name' => 'Setting My Storage'],


//Setting policy and terms
         ['keyword' => 'Setting Policy & Terms', 'translated' => 'Setting Policy & Terms', 'main_section' => 'Settings', 'section_name' => 'Setting Policy & Terms'],
          ['keyword' => 'Policy & Terms', 'translated' => ' Policy & Terms', 'main_section' => 'Settings', 'section_name' => 'Setting Policy & Terms'],


//Setting Contact us
        ['keyword' => 'Setting Contact us', 'translated' => 'Setting Contact us', 'main_section' => 'Settings', 'section_name' => 'Setting Contact Us'],
        ['keyword' => 'Contact Subject', 'translated' => 'Contact Subject', 'main_section' => 'Settings', 'section_name' => 'Setting Contact Us'],
        ['keyword' => 'Online Shop', 'translated' => 'Online Shop', 'main_section' => 'Settings', 'section_name' => 'Setting Contact Us'],
        ['keyword' => 'Servcies', 'translated' => 'Servcies', 'main_section' => 'Settings', 'section_name' => 'Setting Contact Us'],
        ['keyword' => 'Ads', 'translated' => 'Ads', 'main_section' => 'Settings', 'section_name' => 'Setting Contact Us'],
        ['keyword' => 'Account', 'translated' => 'Account', 'main_section' => 'Settings', 'section_name' => 'Setting Contact Us'],
        ['keyword' => 'Payment', 'translated' => 'Payment', 'main_section' => 'Settings', 'section_name' => 'Setting Contact Us'],
        ['keyword' => 'Else', 'translated' => 'Else', 'main_section' => 'Settings', 'section_name' => 'Setting Contact Us'],
        ['keyword' => 'Type the Title', 'translated' => 'Type the Title', 'main_section' => 'Settings', 'section_name' => 'Setting Contact Us'],
        ['keyword' => 'Type the Title here', 'translated' => 'Type the Title here' , 'main_section' => 'Settings', 'section_name' => 'Setting Contact Us'],
        ['keyword' => 'How we can help you', 'translated' => 'How we can help you' , 'main_section' => 'Settings', 'section_name' => 'Setting Contact Us'],
        ['keyword' => 'type here', 'translated' => 'type here' , 'main_section' => 'Settings', 'section_name' => 'Setting Contact Us'],

//Setting About us

        ['keyword' => 'Setting About Us', 'translated' => 'Setting About Us' , 'main_section' => 'Settings', 'section_name' => 'Setting About Us'],
        ['keyword' => 'About us', 'translated' => 'About us' , 'main_section' => 'Settings', 'section_name' => 'Setting About Us'],
        ['keyword' => 'Notes', 'translated' => 'Notes' , 'main_section' => 'Settings', 'section_name' => 'Setting About Us'],






            ['keyword' => 'lost_device', 'translated' => 'Lost Device', 'main_section' => 'Lost Device', 'section_name' => 'Lost Device'],
            ['keyword' => 'login_error_description', 'translated' => 'Login error Device Description', 'main_section' => 'Lost Device', 'section_name' => 'Lost Device'],
            ['keyword' => 'loginerror', 'translated' => 'Login Error', 'main_section' => 'Lost Device', 'section_name' => 'Lost Device'],
            ['keyword' => 'newdevice', 'translated' => 'New  Device', 'main_section' => 'Lost Device', 'section_name' => 'Lost Device'],
            ['keyword' => 'Setup a New  Device', 'translated' => 'Setup a New  Device', 'main_section' => 'Lost Device', 'section_name' => 'Lost Device'],
            ['keyword' => 'Email Verification', 'translated' => 'Email Verification', 'main_section' => 'Lost Device', 'section_name' => 'Lost Device'],
            ['keyword' => 'Email Verification Description', 'translated' => 'Email Verification Description', 'main_section' => 'Lost Device', 'section_name' => 'Lost Device'],
            ['keyword' => 'Type your Email', 'translated' => 'Type your Email', 'main_section' => 'Lost Device', 'section_name' => 'Lost Device'],
            ['keyword' => 'Email sent to', 'translated' => 'Email sent to  ', 'main_section' => 'Lost Device', 'section_name' => 'Lost Device'],
            ['keyword' => 'Code Verification', 'translated' => 'Code Verification  ', 'main_section' => 'Lost Device', 'section_name' => 'Lost Device'],
            ['keyword' => 'Code Verification Description', 'translated' => 'Code Verification Description ', 'main_section' => 'Lost Device', 'section_name' => 'Lost Device'],
            ['keyword' => ' didnot recived the code ', 'translated' => 'I didnot recived the code ', 'main_section' => 'Lost Device', 'section_name' => 'Lost Device'],
            ['keyword' => 'Resend code', 'translated' => 'Resend code  ', 'main_section' => 'Lost Device', 'section_name' => 'Lost Device'],
            ['keyword' => 'second left', 'translated' => 'second left  ', 'main_section' => 'Lost Device', 'section_name' => 'Lost Device'],
            ['keyword' => 'Verifiy now', 'translated' => 'Verifiy now  ', 'main_section' => 'Lost Device', 'section_name' => 'Lost Device'],
            ['keyword' => 'setup a new device', 'translated' => 'setup a new device  ', 'main_section' => 'Lost Device', 'section_name' => 'Lost Device'],
            ['keyword' => 'start now', 'translated' => 'start now', 'main_section' => 'Lost Device', 'section_name' => 'Lost Device'],
            ['keyword' => 'your new device', 'translated' => 'your new device', 'main_section' => 'Lost Device', 'section_name' => 'Lost Device'],
            ['keyword' => 'your_old_device', 'translated' => 'your old device', 'main_section' => 'Lost Device', 'section_name' => 'Lost Device'],

            ['keyword' => 'Take me to signin', 'translated' => 'Take me to signin', 'main_section' => 'Lost Device', 'section_name' => 'Lost Device'],
            ['keyword' => 'Congratulations', 'translated' => 'Congratulations', 'main_section' => 'Lost Device', 'section_name' => 'Lost Device'],
            ['keyword' => 'Congratulations message', 'translated' => 'Congratulations message', 'main_section' => 'Lost Device', 'section_name' => 'Lost Device'],


        ];


        try {
            foreach ($homekeywords as $key => $keyword) {
                $translated = $keyword['translated'];

                LanguageDetail::create([
                    'language_id' => $language_id,
                    'section_name' => $keyword['section_name'],
                    'main_section' => $keyword['main_section'],
                    'keyword' => $keyword['keyword'],
                    'translated' => $translated ?? '',
                ]);
            }
            return 'success';
        } catch (\Exception $e) {
            // Log or handle errors if necessary
            return 'Error: ' . $e->getMessage();
        }
    }

}
